# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QSHBcStWmPFnM3TWRlfQUnO3n9IVZfEr

## Setups and Imports
"""

!pip install -q datasets transformers

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

from datasets import load_dataset, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report, ConfusionMatrixDisplay

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
    EarlyStoppingCallback
)

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

"""## Loading and Preprocessing"""

SEED = 36

# creates a seed reset function to be sure we have the same randomizer always
def set_seed(seed=36):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.use_deterministic_algorithms(True)

# Set SEED 36
set_seed(SEED)

# Load the dataset
print("Loading AG News...")
dataset = load_dataset("sh0416/ag_news")
train_df = pd.DataFrame(dataset["train"])
test_df = pd.DataFrame(dataset["test"])

def clean_text(df):
    # Combine title and description just like in A1
    df["x_text"] = df["title"].astype(str) + " " + df["description"].astype(str)
    # Basic cleaning: lowercase and remove backslashes
    df["x_text"] = df["x_text"].str.replace("\\", " ", regex=False).str.lower()
    return df

train_df = clean_text(train_df)
test_df = clean_text(test_df)

# Split train into train (90%) and validation (10%) using SEED 36
train, val = train_test_split(train_df, test_size=0.1, random_state=SEED)

print(f"Train size: {len(train)} | Val size: {len(val)} | Test size: {len(test_df)}")

train["label"] = train["label"] - 1
val["label"] = val["label"] - 1
test_df["label"] = test_df["label"] - 1

train_tf = train.rename(columns={"x_text": "text"})
val_tf = val.rename(columns={"x_text": "text"})
test_tf = test_df.rename(columns={"x_text": "text"})

train_ds = Dataset.from_pandas(train_tf[["text", "label"]].reset_index(drop=True))
val_ds = Dataset.from_pandas(val_tf[["text", "label"]].reset_index(drop=True))
test_ds = Dataset.from_pandas(test_tf[["text", "label"]].reset_index(drop=True))

"""## Metrics"""

#setting up accuracy function
def accuracy(y_true, y_pred):
    #set y_true and y_pred as numpy arrays so we can use (i, len(y_pred)) as positional arguments
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    #initialize correct prediction count as 0
    same = 0
    for i in range(len(y_pred)):
        if y_true[i] == y_pred[i]:
            #if prediction was right, increse the count
            same += 1
    #return the accuracy
    return same / len(y_pred)

#setting a function that returns True Positives, True Negatives, False Positives and False Negatives, per label
def metrics(label, y_true, y_pred):
    tp = 0
    fp = 0
    fn = 0
    tn = 0
    for yt, yp in zip(y_true, y_pred):
        if yt == label and yp == label:
            tp += 1
        elif yt != label and yp == label:
            fp += 1
        elif yt == label and yp != label:
            fn += 1
        else:
            tn += 1
    return tp, fp, fn, tn

#calculates the f1-score given a label
def f1(label, y_true, y_pred):
    tp, fp, fn, tn = metrics(label, y_true, y_pred)
    precision = tp / (tp + fp) if tp + fp != 0 else 0
    recall = tp / (tp + fn) if tp + fn != 0 else 0
    return 2 * (precision * recall) / (precision + recall)


#calculates the macro f1 (average f1)
def macro_f1(y_true, y_pred):
    labels = sorted(set(y_true) | set(y_pred))
    sum = 0
    for label in labels:
        sum += f1(label, y_true, y_pred)
    return sum / 4

# uses sklearn's confusion matrix function
def conf_matrix(y_true, y_pred, class_names=["World", "Sports", "Business", "Sci/Tech"], normalize=False, save_path=None):
    cm = confusion_matrix(y_true, y_pred)

    if normalize:
        cm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=class_names
    )

    fig, ax = plt.subplots(figsize=(6, 6))
    disp.plot(
        cmap="Blues",
        values_format=".2f" if normalize else "d",
        ax=ax,
        colorbar=True
    )

    #ax.set_title("Normalized Confusion Matrix (Test Set)" if normalize else "Confusion Matrix (Test Set)")
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")

    plt.show()

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)

    return {
        "accuracy": accuracy(labels, preds),
        "macro_f1": macro_f1(labels, preds)
    }

"""## Tokenizer"""

model_checkpoint = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

max_length = 128

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        max_length=max_length
    )

tokenized_train = train_ds.map(tokenize_function, batched=True)
tokenized_val = val_ds.map(tokenize_function, batched=True)
tokenized_test = test_ds.map(tokenize_function, batched=True)

"""## Model"""

model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=4
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

training_args = TrainingArguments(
    output_dir="./agnews_distilbert_50",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)

trainer.train()

"""## Testing"""

test_output = trainer.predict(tokenized_test)
test_logits = test_output.predictions
test_labels = test_output.label_ids
test_preds = np.argmax(test_logits, axis=-1)

print("Test Accuracy:", accuracy(test_labels, test_preds))
print("Test Macro-F1:", macro_f1(test_labels, test_preds))

conf_matrix(test_labels, test_preds)

"""## Robustness/Slice

### Bins
"""

results_df = test_tf.copy().reset_index(drop=True)
results_df["true_label"] = test_labels
results_df["pred_label"] = test_preds
results_df["correct"] = (results_df["true_label"] == results_df["pred_label"]).astype(int)

results_df.head()

results_df["word_count"] = results_df["text"].apply(lambda x: len(str(x).split()))

results_df["length_bucket"] = pd.cut(
    results_df["word_count"],
    bins=[0, 20, 40, 60, 1000],
    labels=["0-20", "21-40", "41-60", "61+"]
)

slice_results = []
for bucket in results_df["length_bucket"].dropna().unique():
    subset = results_df[results_df["length_bucket"] == bucket]
    slice_results.append({
        "length_bucket": str(bucket),
        "n": len(subset),
        "accuracy": accuracy(subset["true_label"].tolist(), subset["pred_label"].tolist()),
        "macro_f1": macro_f1(subset["true_label"].tolist(), subset["pred_label"].tolist())
    })

slice_df = pd.DataFrame(slice_results).sort_values("length_bucket")
slice_df

"""### Reduced size training"""

train_25 = train.sample(frac=0.25, random_state=SEED).reset_index(drop=True)
train_50 = train.sample(frac=0.50, random_state=SEED).reset_index(drop=True)

train_tf_50 = train_50.rename(columns={"x_text": "text"})
train_tf_25 = train_25.rename(columns={"x_text": "text"})

train_ds_50 = Dataset.from_pandas(train_tf_50[["text", "label"]].reset_index(drop=True))
train_ds_25 = Dataset.from_pandas(train_tf_25[["text", "label"]].reset_index(drop=True))

model_checkpoint = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

max_length = 128

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

tokenized_train_50 = train_ds_50.map(tokenize_function, batched=True)
tokenized_train_25 = train_ds_25.map(tokenize_function, batched=True)
tokenized_val = val_ds.map(tokenize_function, batched=True)
tokenized_test = test_ds.map(tokenize_function, batched=True)

"""#### 50%"""

model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=4
)

training_args = TrainingArguments(
    output_dir="./agnews_distilbert_50",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_50,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)

trainer.train()

test_output = trainer.predict(tokenized_test)
test_logits = test_output.predictions
test_labels = test_output.label_ids
test_preds = np.argmax(test_logits, axis=-1)

print("Test Accuracy 50%:", accuracy(test_labels, test_preds))
print("Test Macro-F1 50%:", macro_f1(test_labels, test_preds))

"""#### 25%"""

model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=4
)

training_args = TrainingArguments(
    output_dir="./agnews_distilbert_25",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    greater_is_better=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_25,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=5)]
)

trainer.train()

test_output = trainer.predict(tokenized_test)
test_logits = test_output.predictions
test_labels = test_output.label_ids
test_preds = np.argmax(test_logits, axis=-1)

print("Test Accuracy 25%:", accuracy(test_labels, test_preds))
print("Test Macro-F1 25%:", macro_f1(test_labels, test_preds))

"""## Model states download"""

!zip -r full_training.zip agnews_distilbert

!zip -r 50_training.zip agnews_distilbert_50

!zip -r 25_training.zip agnews_distilbert_25

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!cp /content/25_training.zip /content/drive/MyDrive/
!cp /content/50_training.zip /content/drive/MyDrive/
!cp /content/full_training.zip /content/drive/MyDrive/